require 'ellipsized'
require 'fileutils'
require 'front_matter_parser'
require 'human_number'
require 'json'
require 'time'
require 'tmpdir'

# Load the HumanNumber locale files, as it does not do it automatically.
# TODO: Remove this when human_number will be fixed.
I18n.load_path += Dir[File.join(File.join(Gem::Specification.find_by_name('human_number').gem_dir, 'lib'), 'locales', '*.yml')]

module XAeonAgentsSkills

  # Cline Ruby connector
  class Cline

    include Logger

    # Constructor
    #
    # Parameters::
    # * *api_key* (String): The Cline API key
    def initialize(api_key)
      @api_key = api_key
      @cline_pid = nil
      @task_id = nil
      @next_prompt = nil
      @processing_messages = false
      @remove_conversation_index = nil
    end

    # Send a prompt to a Cline agent
    #
    # Parameters::
    # * *prompt_str* (String): Prompt to be sent
    # * *model* (String): Cline model to be used
    # * *plan_mode* (Boolean): Are we executing in Plan mode? [default: false]
    # * *config* (Hash): Cline config [default: {}]
    # * *skills* (Array<String>): List of skills to activate for this prompt [default: []]
    # * *skillkit_agents* (Boolean): Is AGENTS.md generated by skillkit? If true then a temporary AGENTS.md file will be used to deactivate non-desired skills. [default: false]
    # * *cli_args* (String): Additional CLI arguments [default: '']
    # * *on_message* (Proc or nil): Callback to be called everytime a new message happens in the task being executed, or nil if no callback [default: nil]
    #   * Parameters::
    #     * *message* (Hash): Message that has happened
    #     * *last* (Boolean): Is this the last message fetched?
    #     * *previous_version* (Hash or nil): Previous version of this message if it got updated, or nil if it is a new one
    #     * *usage* (Hash<Integer,Hash<Symbol,Object>>): Information on the usage, per timestamp. The information can have the following properties:
    #       * *cost* (Float): Query cost, in $.
    #       * *input_tokens* (Integer): Input tokens of the query
    #       * *output_tokens* (Integer): Output tokens of the query
    #       * *cache_read_tokens* (Integer): Cache read tokens of the query
    #       * *cache_write_tokens* (Integer): Cache write tokens of the query
    #       * *context_tokens* (Integer): Size of the context
    #       * *context_tokens_limit* (Integer): Limit of the size of the context
    # * *stdout_echo* (Boolean): Do we echo stdout of Cline CLI? [default: false]
    # * *ignore_partials* (Boolean): Should we ignore partial messages? If true, then on_message will only be called for messages that have been fully received. [default: false]
    def prompt(prompt_str, model:, plan_mode: false, config: {}, skills: [], skillkit_agents: false, cli_args: '', on_message: nil, stdout_echo: false, ignore_partials: false)
      Helpers.with_temp_dir(sub_dir: 'tmp/cline') do |temp_dir|
        config_dir = "#{temp_dir}/cline_config"
        log_debug "Temporary Cline config dir: #{config_dir}"

        # Authenticate and generate the configuration directory
        system "cline auth --config #{config_dir} --provider cline --apikey #{@api_key} --modelid #{model}", exception: true
        log_debug "Cline CLI authenticated successfully in config dir #{config_dir} for model #{model}"

        # Merge configuration options from payload into the globalState.json file
        global_state_path = "#{config_dir}/data/globalState.json"
        File.write(
          global_state_path,
          JSON.pretty_generate(
            Helpers.deep_merge(
              JSON.parse(File.read(global_state_path)),
              config
            )
          )
        )

        with_selected_skills(skills, config_dir:, skillkit_agents:) do
          with_messages_monitoring(config_dir:, model:, on_message:, ignore_partials:) do
            @task_id = nil
            begin
              @next_prompt = prompt_str
              idx_prompt = 0
              while !@next_prompt.nil? && @next_prompt != :exit
                # Generate prompt file
                prompt_file = "#{temp_dir}/prompt_#{idx_prompt}.txt"
                # Make sure we always create Unix-style files.
                File.write(prompt_file, @next_prompt.is_a?(String) ? @next_prompt.gsub("\r", '') : JSON.pretty_generate(@next_prompt), mode: 'wb')
                @next_prompt = nil
                @remove_conversation_index = nil
                idx_prompt += 1
                run_status = {}
                begin
                  # Run the agent
                  cmd = "cline --config #{config_dir} #{plan_mode ? '--plan' : '--act'} #{Logger.debug ? '--verbose' : ''} --json #{cli_args} #{@task_id.nil? ? '' : "--taskId #{@task_id}"} < #{prompt_file}"
                  log_debug "Cline CLI: #{cmd}"
                  run_status = XAeonAgentsSkills::Helpers.run_cmd(
                    cmd,
                    expected_exit_status: nil,
                    on_start: proc do |_stdin, _stdout, _stderr, wait_thr|
                      @cline_pid = wait_thr.pid
                    end,
                    on_stdout: proc do |line|
                      puts line if stdout_echo
                      if line =~ /^\{"type":"task_started","taskId":"(\d+)"\}$/
                        @task_id = Integer(Regexp.last_match[1])
                        log_debug "Started task ID #{@task_id}"
                      end
                    end,
                    on_stderr: proc { |line| $stderr.puts line }
                  )
                ensure
                  @cline_pid = nil
                end
                # Wait for the messages thread to stop processing messages
                sleep 0.1 while @processing_messages
                # In case of errors, we may have to remove some conversations
                unless @remove_conversation_index.nil?
                  log_debug "Remove conversation #{@remove_conversation_index} from task's messages"
                  File.write(
                    current_task_messages_file(config_dir),
                    current_task_messages(config_dir).
                      select { |message| message[:conversationHistoryIndex] != @remove_conversation_index }.
                      to_json
                  )
                end
                # If we are having a next prompt, then we can ignore the exit status.
                # The process could have been interrupted on purpose, or because of an error that we want to retry.
                raise "Unexpected exit status: #{run_status[:exit_status]}" if @next_prompt.nil? && run_status[:exit_status] != 0
              end
            ensure
              @task_id = nil
            end
          end
        end
      end
    end

    # Give some user feedback on a running task.
    # This will interrupt the current task, and resume it with the user feedback.
    #
    # Parameters::
    # * *message* (String or Synbol): The feedback to append, or symbols for some commands:
    #   * *exit*: Interrupt the task
    def user_feedback(message)
      raise 'No task current running' if @cline_pid.nil?
      log_debug "=> Send user feedback #{message}"
      @next_prompt = message
      log_debug "Interrupt current task with PID #{@cline_pid}"
      if Gem.win_platform?
        system("taskkill /PID #{@cline_pid} /T /F 2>&1 || exit /B 0", exception: true)
      else
        Process.kill('INT', @cline_pid)
      end
    end

    # Return the list of Cline models information.
    # Keep a cache of it.
    #
    # Result::
    # * Hash<String,Hash<Symbol,Object>>: Each model's information, per model name
    def self.models
      @cached_models ||= JSON.parse(File.read("#{ENV['VSCODE_PORTABLE'] ? "#{ENV['VSCODE_PORTABLE']}/user-data" : "#{ENV['APPDATA']}/Code"}/User/globalStorage/saoudrizwan.claude-dev/cache/cline_models.json"), symbolize_names: true).transform_keys(&:to_s)
    end

    private

    # Use a single regex to match complete tag pairs
    # This regex matches <tag>content</tag> patterns
    COMPLETE_TAG_PATTERN = %r{<([a-zA-Z0-9_:]*)>(.*?)</\1>}m

    # Parse sections from a string with HTML-like tags.
    # Sections are delimited by html-like tags, for example `<toto>...</toto>` is the section named `toto`.
    # Sections without tags should still be part of the result, with a nil section name.
    # Only considers top-level tags (no recursion).
    #
    # Parameters::
    # * *content* (String): The input string to parse
    # Result::
    # * Array<Hash>: List of sections:
    #   * *name* (String or nil): Section name
    #   * *content* (String): Section content
    def parse_sections(content)
      sections = []
      current_pos = 0
      content_length = content.length
      # Use cursor progression to maintain order
      while current_pos < content_length
        # Find the next complete tag pair starting from current position
        match = content.match(COMPLETE_TAG_PATTERN, current_pos)
        if match
          # Add any untagged content before this tag
          if match.begin(0) > current_pos
            untagged_content = content[current_pos...match.begin(0)]
            sections << { name: nil, content: untagged_content } unless untagged_content.strip.empty?
          end
          # Add the tagged section
          sections << { name: match[1], content: match[2] }
          current_pos = match.end(0)
        else
          # No more tags found, add remaining content
          remaining_content = content[current_pos..-1]
          sections << { name: nil, content: remaining_content } unless remaining_content.strip.empty?
          current_pos = content_length
        end
      end
      sections
    end

    # Return a human-friendly version of a message.
    # Useful for stdout or logging.
    #
    # Parameters::
    # * *message* (Hash): Message to translate to humans
    # * *usage* (Hash): Usage statistics of the current prompt
    # * *limit* (Integer): Number of characters the message should be limited to [default: 128]
    # Result::
    # * String: The human translation
    def human_message(message, usage:, limit: 128)
      last_usage = usage.values.last
      prefix = "[#{Time.at(message[:ts] / 1000.0).strftime('%H:%M:%S')}]#{
        if last_usage.nil?
          ''
        else
          " (#{HumanNumber.currency(usage.values.map { |stats| stats[:cost] || 0.0 }.sum, currency_code: 'USD')} #{HumanNumber.human_number(last_usage[:context_tokens], max_digits: 2)}/#{HumanNumber.human_number(last_usage[:context_tokens_limit], max_digits: 2)})"
        end
      } - "
      "#{prefix}#{
        case message[:type]
        when 'say'
          case message[:say]
          when 'text', 'task'
            one_lining(message[:text])
          when 'api_req_started'
            sections = parse_sections(JSON.parse(message[:text], symbolize_names: true)[:request])
            section_delimiter = '|'
            # Ignore some sections
            sections.select! { |section| section[:name] != 'environment_details' }
            section_size = (limit - prefix.size) / sections.size - section_delimiter.size
            sections.map do |section|
              "#{section[:name].nil? ? '' : "#{section[:name]}: "}#{one_lining(section[:content])}".ellipsized(section_size)
            end.join('|')
          when 'tool'
            tool_details = JSON.parse(message[:text], symbolize_names: true)
            tool_header =
              case tool_details[:tool]
              when 'readFile'
                "[readFile] - #{tool_details[:path]}"
              when 'listFilesRecursive'
                "[listFilesRecursive] - #{tool_details[:path]}"
              when 'listFilesTopLevel'
                "[listFilesTopLevel] - #{tool_details[:path]}"
              when 'newFileCreated'
                "[newFileCreated] - #{tool_details[:path]}"
              when 'editedExistingFile'
                "[editedExistingFile] - #{tool_details[:path]}"
              when 'searchFiles'
                "[searchFiles] - #{tool_details[:path]} (regex: #{tool_details[:regex]})"
              when 'useSkill'
                "[useSkill] - #{tool_details[:skill_name]}"
              else
                raise NotImplementedError.new("Unknown tool @ts #{message[:ts]}: #{message}")
              end
            "#{tool_header}#{tool_details.key?(:content) ? ": #{one_lining(tool_details[:content])}".ellipsized(limit - prefix.size - tool_header.size) : ''}"
          when 'api_req_retried'
            'API request retried'
          when 'command'
            "Command: #{one_lining(message[:text])}"
          when 'command_output'
            "Command output: #{one_lining(message[:text])}"
          when 'diff_error'
            "Diff error: #{one_lining(message[:text])}"
          when 'error_retry'
            "Error retry: #{one_lining(message[:text])}"
          when 'reasoning'
            "Reasoning: #{one_lining(message[:text])}"
          when 'user_feedback'
            "User feedback: #{one_lining(message[:text])}"
          when 'task_progress'
            # Count completed vs total tasks
            completed_tasks = message[:text].scan(/- \[x\]/).size
            total_tasks = message[:text].scan(/- \[[ x]\]/).size
            "Task progress: #{completed_tasks}/#{total_tasks} tasks"
          when 'completion_result'
            "Task completed: #{one_lining(message[:text])}"
          when 'error'
            "Error: #{one_lining(message[:text])}"
          else
            raise NotImplementedError.new("Unknown say @ts #{message[:ts]}: #{message}")
          end
        when 'ask'
          "Ask user: #{
            case message[:ask]
            when 'resume_task'
              'Resume task'
            when 'resume_completed_task'
              'Resume completed task'
            when 'api_req_failed'
              details = JSON.parse(message[:text], symbolize_names: true)
              "API request failed - #{details[:code]} - #{one_lining(details[:message])}"
            when 'command_output'
              "Command output - #{one_lining(message[:text])}"
            when 'completion_result'
              'Completion result'
            when 'followup'
              details = JSON.parse(message[:text], symbolize_names: true)
              "Follow-up - #{details[:question]}#{details[:options].nil? || details[:options].empty? ? '' : " - Options: #{details[:options].join(', ')}"}"
            when 'plan_mode_respond'
              details = JSON.parse(message[:text], symbolize_names: true)
              "Plan mode respond - #{one_lining(details[:response])}}"
            when 'tool'
              details = JSON.parse(message[:text], symbolize_names: true)
              tool_name = details.delete(:tool)
              "Use tool - #{tool_name} - #{details.to_json}}"
            when 'mistake_limit_reached'
              "Mistake limit reached - #{one_lining(message[:text])}}"
            when 'new_task'
              "New task - #{one_lining(message[:text])}"
            else
              raise NotImplementedError.new("Unknown ask @ts #{message[:ts]}: #{message}")
            end
          }"
        else
          raise NotImplementedError.new("Unknown type @ts #{message[:ts]}: #{message}")
        end
      }".ellipsized(limit)
    end

    # Convert a string to a single line by replacing newlines with spaces and removing carriage returns
    #
    # Parameters::
    # * *text* (String): The text to convert to one line
    # Result::
    # * String: The text converted to a single line
    def one_lining(text)
      text.strip.gsub("\n", ' ').gsub("\r", '')
    end

    # Get the current task messages file
    #
    # Parameters::
    # * *config_dir* (String): Cline config dir
    # Result::
    # * String: Task's messages file
    def current_task_messages_file(config_dir)
      "#{config_dir}/data/tasks/#{@task_id}/ui_messages.json"
    end

    # Get the current task messages
    #
    # Parameters::
    # * *config_dir* (String): Cline config dir
    # Result::
    # * Array<Hash>: List of task's messages
    def current_task_messages(config_dir)
      JSON.parse(safe_read(current_task_messages_file(config_dir)), symbolize_names: true)
    end

    # Monitor messages arriving for a task and call a callback for each one of them.
    # Also monitor for potential errors so that we provide a retry mechanism.
    #
    # Parameters::
    # * *config_dir* (String): Configuration from which the task should be found
    # * *model* (String): Cline model to be used
    # * *on_message* (Proc or nil): Callback to be called everytime a new message happens in the task being executed, or nil if no callback [default: nil]
    #   * Parameters::
    #     * *message* (Hash): Message that has happened
    #     * *last* (Boolean): Is this the last message fetched?
    #     * *previous_version* (Hash or nil): Previous version of this message if it got updated, or nil if it is a new one
    #     * *usage* (Hash): Usage statistics
    # * *ignore_partials* (Boolean): Should we ignore partial messages? If true, then on_message will only be called for messages that have been fully received. [default: false]
    # * Proc: Code called with monitoring in place
    def with_messages_monitoring(config_dir:, model:, on_message: nil, ignore_partials: false)
      monitoring = true
      @processing_messages = true
      monitoring_thread = Thread.new do
        ui_messages_file = nil
        ui_messages_file_mtime = nil
        usage = {}
        # Keep messages per timestamp to detect updates
        messages = {}
        while monitoring
          unless @task_id.nil?
            ui_messages_file = current_task_messages_file(config_dir)
            new_ui_messages_file_mtime = File.mtime(ui_messages_file)
            if new_ui_messages_file_mtime == ui_messages_file_mtime
              @processing_messages = false
            else
              @processing_messages = true
              # New messages have been added or old ones were updated
              new_messages = current_task_messages(config_dir)
              new_messages.select! { |message| message[:partial].nil? || !message[:partial] } if ignore_partials
              unless new_messages.empty?
                last_idx = new_messages.size - 1
                new_messages.each.with_index do |message, idx|
                  ts = message[:ts]
                  if message != messages[ts]
                    log_debug { human_message(message, usage:, limit: 128) }
                    # Handle usage tracking
                    if message[:type] == 'say' && message[:say] == 'api_req_started'
                      api_details = JSON.parse(message[:text], symbolize_names: true)
                      usage[messages[ts]] = {
                        cost: api_details[:cost],
                        input_tokens: api_details[:tokensIn],
                        output_tokens: api_details[:tokensOut],
                        cache_read_tokens: api_details[:cacheReads],
                        cache_write_tokens: api_details[:cacheWrites],
                        context_tokens: %i[tokensIn tokensOut cacheReads cacheWrites].map { |token_measure| api_details[token_measure] || 0 }.sum,
                        context_tokens_limit: Cline.models[model][:contextWindow]
                      }.compact
                    end
                    on_message.call(message, idx == last_idx, messages[ts], usage) unless on_message.nil?
                    # Handle errors
                    if message[:say] == 'error'
                      # If we are encountering an error, be prepared for the process to exit with code 1 and retry.
                      # The way to retry after an error is to tell the agent about the error, and delete the conversation task that lead to the error before retrying.
                      @remove_conversation_index = message[:conversationHistoryIndex]
                      @next_prompt = <<~EO_Prompt
                        A previous task execution returned this error: \"#{message[:text]}\".
                        Be careful to not run into this error again and continue your task.
                      EO_Prompt
                      log_debug "Retry because of error on conversation #{@remove_conversation_index}: #{message[:text]}."
                    end
                    messages[ts] = message
                  end
                end
              end
              ui_messages_file_mtime = new_ui_messages_file_mtime
            end
          end
          sleep 1
        end
        @processing_messages = false
      end
      begin
        yield
      ensure
        monitoring = false
        monitoring_thread.join
        @processing_messages = false
      end
    end

    # Call some code with Cline configured to run only with some selected skills.
    # This requires to generate the config file with all other skills to be disabled.
    # In case of skillkit usage, it also requires to alter the AGENTS.md file by generating another temporary one.
    #
    # Parameters::
    # * *skills* (Array<String>): List of skills to activate for this prompt
    # * *config_dir* (String): Configuration directory
    # * *skillkit_agents* (Boolean): Is AGENTS.md generated by skillkit? If true then a temporary AGENTS.md file will be used to deactivate non-desired skills. [default: false]
    # * Proc: Code called with skills setup properly
    def with_selected_skills(skills, config_dir:, skillkit_agents: false)
      # Select the skills to be hidden, so that only the selected ones are available to our agent
      selected_skills = skills.dup
      skills.each do |skill|
        dependent_skills(skill, selected_skills)
      end
      log_debug "#{selected_skills.size} selected skills: #{selected_skills.join(', ')}"
      all_skills = Dir['.cline/skills/*'].map { |skill_dir| File.basename(skill_dir) }
      missing_skills = selected_skills - all_skills
      raise "#{missing_skills.size} missing skills: #{missing_skills.join(', ')}" unless missing_skills.empty?
      hidden_skills = all_skills - selected_skills
      log_debug "#{hidden_skills.size} skills to disable: #{hidden_skills.join(', ')}"

      # Set the workspace config, dealing with disabled rules and skills
      workspace_config = {
        localSkillsToggles: hidden_skills.to_h do |skill|
          [
            canonize_path(".cline/skills/#{skill}/SKILL.md"),
            false
          ]
        end
      }

      temp_agents_file = nil
      if skillkit_agents
        # We have to replace the AGENTS.md file with another version that is specific to this run and only has the selected skills.
        temp_agents_file = ".clinerules/x-aeon-agents/AGENTS-#{unique_id { |id| !File.exist?(".clinerules/x-aeon-agents/AGENTS-#{id}.md") }}.md"
        agents_content = File.read('AGENTS.md')
        hidden_skills.each do |skill|
          escaped_skill = Regexp.escape(skill)
          agents_content.gsub!(/- \*\*#{escaped_skill}\*\*: [^\n]+\n/, '')
          agents_content.gsub!(/<skill>\n<name>#{escaped_skill}<\/name>.+?<\/skill>\n\n/m, '')
        end
        # Alter the workspace config accordingly to use this temporary AGENTS.md file
        workspace_config.merge!(
          localClineRulesToggles: {
            canonize_path(temp_agents_file) => true
          },
          localAgentsRulesToggles: {
            canonize_path('AGENTS.md') => false
          }
        )
        # Create the temporary AGENTS.md file
        FileUtils.mkdir_p File.dirname(temp_agents_file)
        File.write(temp_agents_file, agents_content)
      end

      begin
        # Create the workspace configuration file
        File.write(
          "#{Dir["#{config_dir}/data/workspaces/*"].first}/workspaceState.json",
          JSON.pretty_generate(workspace_config)
        )
        yield
      ensure
        FileUtils.rm_f(temp_agents_file) unless temp_agents_file.nil?
      end
    end

    # Get a full file path as Cline config file is expecting it
    #
    # Parameters::
    # * *path* (String): A file path
    # Result::
    # * String: The corresponding file path that can be included in Cline config files
    def canonize_path(path)
      File.expand_path(path).gsub(File::SEPARATOR, File::ALT_SEPARATOR || File::SEPARATOR)
    end

    # Find a unique ID, with a client code block validating its unicity.
    #
    # Parameters::
    # * Proc: Code validating unicity
    #   * Parameters::
    #     * *id* (String): ID to validate the unicity of
    #   * Result::
    #     * Boolean: Is the ID unique?
    def unique_id
      id = nil
      unique_idx = 0
      loop do
        id = "#{Time.now.strftime('%Y-%m-%d-%H-%M-%S')}-#{unique_idx}"
        break if yield(id)
        unique_idx += 1
      end
      id
    end

    # Get all skills dependencies recursively from a skill.
    # Handle cyclic dependencies.
    #
    # Parameters::
    # * *skill* (String): Skill
    # * *found_skills* (Array<String>): In place array of skills that have already been found as dependencies
    def dependent_skills(skill, found_skills)
      deps = FrontMatterParser::Parser.parse_file(".cline/skills/#{skill}/SKILL.md").front_matter.dig('metadata', 'dependencies')
      unless deps.nil?
        deps.each do |skill_dep|
          skill_dep_name = skill_dep.include?(':') ? skill_dep.match(/^[^:]+:(.+)$/)[1] : skill_dep
          unless found_skills.include?(skill_dep_name)
            found_skills << skill_dep_name
            dependent_skills(skill_dep_name, found_skills)
          end
        end
      end
    end

    # Try to read a file with retries in case other processes are using it.
    #
    # Parameters::
    # * *file* (String): Path to read
    # * *max_retries* (Integer): Number of retries in case of concurrent access [default: 3]
    # Result::
    # * String: The file content
    def safe_read(file, max_retries: 3)
      retries = 0
      file_content = nil
      begin
        file_content = File.read(file)
      rescue Errno::EACCES, Errno::EAGAIN
        # Could be that the file is being written at the same time.
        # Just try again.
        retries += 1
        raise if retries > max_retries
        sleep(0.05 * retries)
        retry
      end
      file_content
    end

  end

end
